### ISSUE TITLE
putFile method calls can't be called in parallel

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#118]
If an app calls putFile twice in a row then it is possible that only the last one is properly finished.

Steps to reproduce:
In the example make two putFile calls with different names. See that only the last one is finished successfully. The other never returns.

Thanks to @AC-FTW as mentioned in https://forum.blockstack.org/t/blockstack-android-api-0-4-1-writes-to-gaia-failing/6853

**Comment by friedger** [comment]
This is due to the way how the Android SDK implements the fetch (from javascript). It stores the promise with a normalized url, as a putFile call requires a read the gaia hub the second putFile overwrites the promise for the first gaia hub fetch call. Hence, the first fetch promise is never resolved and the first putFile never finishes.

**Comment by AC-FTW** [comment]
I've updated to @shreyasthiagaraj merge of @friedger 's fix and it's looking good so far. Thank you both!
