### ISSUE TITLE
As a developer, I want to better understand which callbacks run in which threads

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#12]
In most callbacks it is necessary to user `runOnUIThread`.

This should be documented or the SDK should call the callbacks from the UI thread already.

**Comment by larrysalibra** [comment]
Thanks @friedger - i made a note of this in the comments.

**Comment by larrysalibra** [comment]
Going to close this issue. Please open a new issue if you think think it would be better to set these callbacks up to run on the UI thread and let me know if you'd like to take a stab at it.
