### ISSUE TITLE
Document export restrictions and android apps

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-android#121]
There are some responsibilities for exporting android apps.  We should document these.

**Comment by friedger** [comment]
See for example
https://stackoverflow.com/questions/2128927/using-ssl-in-an-iphone-app-export-compliance

And there is also the Australien non-encryption regulations..

**Comment by friedger** [comment]
fixed by https://github.com/blockstack/blockstack-android/commit/54a9488ae8c90035302ef371cc9bfb6c59f3776e
