### ISSUE TITLE
NoSuchMethodException for the method "log" in BlockstackSession.kt

### ISSUE THREAD

**Issue by altuncu** [blockstack/blockstack-android#124]
When I upgraded the version of Blockstack Android SDK in my app to 0.4.2, the line in the given example
`_blockstackSession = BlockstackSession(context, config) ` gives the error like the following:

`java.lang.IllegalStateException: java.lang.NoSuchMethodException: log [class java.lang.String]`
       ` at com.eclipsesource.v8.V8Object.registerJavaMethod(V8Object.java:637)`
       ` at com.eclipsesource.v8.V8Object.registerJavaMethod(V8Object.java:612)`
        `at org.blockstack.android.sdk.BlockstackSession.registerConsoleMethods(BlockstackSession.kt:137)`
        `at org.blockstack.android.sdk.BlockstackSession.<init>(BlockstackSession.kt:76)`
       ` at org.blockstack.android.sdk.BlockstackSession.<init>(BlockstackSession.kt:48)`

**Comment by friedger** [comment]
Thank you for reporting. Which example are you running?

**Comment by altuncu** [comment]
Actually, I'm trying to use the SDK in my app. I mostly use the code of the project "example". It was working in 0.3.0 but doesn't work in 0.4.2 because of that runtime error. After the upgrade, I changed the config parts to `toBlockstackConfig()` method and the SDK version in gradle.

**Comment by friedger** [comment]
@altuncu My understanding is that this has been solved. If not please reopen the issue
