### ISSUE TITLE
Invalid redirect url during onboarding

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-android#125]
Here is the `redirect.html` file for the webapp example in the Android SDK:
https://github.com/blockstack/blockstack-android/blob/master/tools/blockstack-android-web-app/public/redirect.html

This line: `window.location="myblockstackapp:" + authResponse` is incorrect. The format should match the one in iOS: `window.location="myblockstackapp://?authResponse=" + authResponse`.

Due to this issue Android and iOS SDK examples cannot share the same web app. Following this correction the SDK's methods to handle sign in and parse the auth response will also likely need to be updated.

**Comment by shreyasthiagaraj** [comment]
Sure, what is your suggestion?

**Comment by friedger** [comment]
https://tools.ietf.org/html/rfc3986#section-3 specifies that an uri is
```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
``` 
I'd suggest `myblockstack:ey....` or if you want an authority in the uri `myblockstack:\\app_domain?authResponse=ey....` or `myblockstack:?authRespons=ey....`

**Comment by shreyasthiagaraj** [comment]
@friedger , sure, `myblockstackapp:?authResponse=` should work

**Comment by friedger** [comment]
Let's do that then. Maybe use different schema? blockstacksample
