### ISSUE TITLE
As a user, I am confused when I am not redirected to the app after login

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#135]
This is somewhat related to #7 

As a user, I am confused that the login flow does not take me to the app again but stays within the browser.

This can happen because the Android SDK uses CustomTabs for redirect to browser.blockstack.org.

The solution is to use [verified app links](https://developer.android.com/training/app-links/verify-site-associations). 

Todo:
* document this well for developers
* add warning in the SDK if links are not verified.

**Comment by GInxh** [comment]
Thanks friedgar, I will send this along and make sure it gets in front of the right people.

**Comment by friedger** [comment]
Warning added, documentation improved
