### ISSUE TITLE
As a developer and user, I want to use a blockstack themed sign in button

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#14]
The SDK should contain a styled sign-in button

**Comment by larrysalibra** [comment]
This is a great idea!

**Comment by larrysalibra** [comment]
![img_6392](https://user-images.githubusercontent.com/597182/41846983-caa8e72e-7878-11e8-8317-f6699918aa21.jpg)
![img_6393](https://user-images.githubusercontent.com/597182/41846985-ccc6f91a-7878-11e8-9bb1-1a2043eb0bc4.jpg)


Thanks to @friedger we now have a beautiful styled sign in button! This will ship in the next release.
