### ISSUE TITLE
Add url param for client during auth request

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-android#141]
Currently for ios we're sending `client=ios_secure`, it'd be great to pass along something like `client=android`.

**Comment by friedger** [comment]
@aulneau Could you please add some more background? Custom parameters can be added with a custom auth request.

**Comment by friedger** [comment]
Currently, we rely on blockstack.js to redirect to signin. There is no logic to add additional parameters to the redirect to httpsURI.

Potentially addressing this in the future by pointing the AndroidSDK to a different path for auth e.g. `browser.blockstack.org/auth_mobile`
