### ISSUE TITLE
App Link Verifier Failed Error

### ISSUE THREAD

**Issue by altuncu** [blockstack/blockstack-android#146]
When I run my application, it crashes after calling `redirectToSignIn()` by giving the following error:

`AppLinkVerifier: Failed to check verified app links. javax.net.ssl.SSLProtocolException: Read error: ssl=0xcf29f3c0: Failure in SSL library, usually a protocol error`
`error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.cc:717 0xde3b5dc3:0x00000000)`
 `javax.net.ssl.SSLProtocolException: Read error: ssl=0xcf29f3c0: Failure in SSL library, usually a protocol error`
`error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.cc:717 0xde3b5dc3:0x00000000)`
        `at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)`
       ` at com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:384)`
        `at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:541)`
        `at com.android.okhttp.okio.Okio$2.read(Okio.java:136)`
        `at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)`
        `at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)`
`at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)`
`at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)`
`at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)`
`at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)`      
  `at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)`
`    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)`
` at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)`
`at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)`
`        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)`
`        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)`
`        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)`
       ` at java.net.URL.openStream(URL.java:1058)`
        `at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:150)`
`        at org.blockstack.android.sdk.AppLinkVerifier.getFingerprintFromDigitalAssetLinksFile(AppLinkVerifier.kt:69)`
`        at org.blockstack.android.sdk.AppLinkVerifier.verify(AppLinkVerifier.kt:38)`
`        at org.blockstack.android.sdk.BlockstackSession$1.invokeSuspend(BlockstackSession.kt:129)`  
     ` at org.blockstack.android.sdk.BlockstackSession$1.invoke(Unknown Source:10)`
`        at org.blockstack.android.sdk.AndroidExecutor$onNetworkThread$1.invokeSuspend(BlockstackSession.kt:1014)`
       ` at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`
        `at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)`
        `at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)`
`        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)`
        `at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

My app link is https://blocksignal.netlify.com. I can verify this link through App Link Assistant in Android Studio. Also, I added the following line to my Manifest file:

`<data android:scheme="https" android:host="blocksignal.netlify.com" />`

**Comment by friedger** [comment]
A quick fix would be to set the flag
BlockstackSession.doNotVerifyAppLinkVerification to true

**Comment by friedger** [comment]
The message is only a warning. The app does not crash for this reason.
It looks like that this happened when Google was down.
