### ISSUE TITLE
App link verifier does not support multiple fingerprints per app

### ISSUE THREAD

**Issue by sdsantos** [blockstack/blockstack-android#147]
The app link verifier added by #136 is useful, but right now it's not supporting multiple `sha256_cert_fingerprints` under the same app package name, like one could have for the debug and release version of an app.

The statements from Google's verifier becomes something like:

```
{
  "statements": [
    {
      "source": {
        "web": {
          "site": "https://example.com"
        }
      },
      "relation": "delegate_permission/common.handle_all_urls",
      "target": {
        "androidApp": {
          "packageName": "com.example",
          "certificate": {
            "sha256Fingerprint": "14:6D:E9:83:C5:73:06:50:D8:EE:B9:95:2F:34:FC:64:16:A0:83:42:E6:1D:BE:A8:8A:04:96:B2:3F:CF:44:E5"
          }
        }
      }
    },
    {
      "source": {
        "web": {
          "site": "https://example.com."
        }
      },
      "relation": "delegate_permission/common.handle_all_urls",
      "target": {
        "androidApp": {
          "packageName": "com.example.app",
          "certificate": {
            "sha256Fingerprint": "AB:CD:EF:00:11:22:06:50:D8:EE:B9:95:2F:34:FC:64:16:A0:83:42:E6:1D:BE:A8:8A:04:96:B2:3F:CF:44:E5"
          }
        }
      }
    }
  ]
}
```

**Comment by friedger** [comment]
The added statement is only for the web server that serves for the examples of this repo. They are not supposed to run in production.  On production servers, the file will probably look different.

**Comment by sdsantos** [comment]
@friedger Not sure I understand what you are mentioning, which file will look different in production servers?

Multiple `sha256_cert_fingerprints` is a common case in app development. I had a `debug` and a `release` environment, and I needed both to be verified so the blockstack authentication could work smoothly. Therefore I needed multiple fingerprints on the `assetlinks.json` file. The `blockstack-android` app link verifier was stating that the auto verification wasn't setup correctly, when in fact it was. It's the verifier that is not suporting multiple fingerprints.

**Comment by friedger** [comment]
@sdsantos Thank you for the clarification. I misunderstood the issue.

**Comment by friedger** [comment]
Fixed by https://github.com/blockstack/blockstack-android/commit/2d43bfcff7594084d9299fd2be511e7061cfee83
