### ISSUE TITLE
HTTP requests block thread on error

### ISSUE THREAD

**Issue by sdsantos** [blockstack/blockstack-android#150]
If there's an error when making a network call with Blockstack, the thread just blocks and there's no feedback, exception or callback called. This is an issue I've ran into when trying to handle scenarios without network connection.

Here's my ugly workaround just to get the error callback called:
https://github.com/blockstack/blockstack-android/compare/master...sdsantos:fix-network-thread

Am I missing something or is this something that needs some work?

**Comment by friedger** [comment]
Thank you for reporting. Is the thread really blocked? I would assume that it just ends without coming back to the Android app. I'll try to add a test for that and incorporate your solution.

**Comment by sdsantos** [comment]
@friedger I'm didn't confirmed if it's actually `blocked`, meaning you can't do any other work on the network thread. But you do lose any way of knowing the state of that request.

**Comment by jeffdomke** [comment]
@friedger can we close this?

**Comment by friedger** [comment]
Fixed by #153 
Will be shipped in next version.
