### ISSUE TITLE
Login redirect to the app issue

### ISSUE THREAD

**Issue by arinyguedes** [blockstack/blockstack-android#152]
I am trying to work with Blockstack on Android, but the login is not working properly.
 
I tried the code available on https://docs.blockstack.org/android/tutorial.html. 

The sign in button redirects me to Chrome, I can choose a Blockstack account then I am redirected properly with authResponse token as an argument on the query string, BUT it is not returning to the app. 

So, I evaluated the code, debugged and I could see that the onNewIntent method and onCreate method are not called after that redirect and one of them is supposed to be. I am using Android 9. 

I saw some issues related, but I could not figure out the problem even because I am using the example code "as is".

**Comment by sdsantos** [comment]
That issue is very likely related with the App link setup: https://github.com/blockstack/blockstack-android#redirect-with-app-links

Do you have any warning when opening the app first time, about if the App links are setup correctly?

**Comment by arinyguedes** [comment]
I did not see any warning :/
Following your link I added the tag on the view intent-filter: <data android:scheme="https" android:host="flamboyant-darwin-d11c17.netlify.com" />
But it still is not working.

**Comment by friedger** [comment]
I understand that after the redirect the user is staying in Chrome,
probably seeing the authResponse token in the url bar.

Can you please verify that the fingerprints are matching?

**Comment by altuncu** [comment]
To add a verified app link, you should add your app's fingerprint to the flamboyant.... website's assetlinks.json file. But, it's not possible to change it as you don't control that domain. So, either deploy your own sign in app in a domain that you control (codes of the existing sign in app is available) or disable verified app links feature in the code. You can find more details on verified app links on https://developer.android.com/training/app-links/verify-site-associations

**Comment by arinyguedes** [comment]
Thank you! Following the link, I could understand the problem. I published a domain with the properly assetlinks.json and it worked!
I suggest updating the tutorial with that explanation. Because when someone downloads the example and try to run "as is" it will not work.

**Comment by friedger** [comment]
I created an issue to update the android tutorial: https://github.com/blockstack/docs.blockstack/issues/289
