### ISSUE TITLE
Missing signature parameter in PutFileOptions

### ISSUE THREAD

**Issue by altuncu** [blockstack/blockstack-android#156]
https://github.com/blockstack/blockstack-android/blob/4900e95865142112ee8f4f5c4ced90806a2108a9/blockstack-sdk/src/main/java/org/blockstack/android/sdk/model/PutFileOptions.kt#L11

The referenced code should also include a sign parameter as in blockstack.js library.

**Comment by jeffdomke** [comment]
@friedger is this good to close? @altuncu are you good?

**Comment by altuncu** [comment]
It seems good

**Comment by friedger** [comment]
Fixed by #157
