### ISSUE TITLE
Improve handling of activity context on redirectToSignIn

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#159]
Currently, a BlockstackSession is created with a context parameters. The context is used to redirect the user to the blockstack browser via startActivity, therefore, the context needs to be an activity. However, for all other use cases the application context would be sufficient (to lookup resources mainly). If only the application context is needed the same BlockstackSession could be used across activities.

(this continues the discussion on #151 with @sdsantos )

**Comment by friedger** [comment]
@sdsantos 
>why would the user experience suffer with 1)? 
Going back would close the browser and not back to the app.

>And why should the BlockstackSession only belong to a  single activity? Isn't it meant to be used throughout the app? I feel  like belonging to the Application Context makes more sense.
My understanding of the app architecture is that some components (activities, services) of the app deal with blockstack, others don't. Therefore, it makes sense to just keep it local to the component. Maybe that is a not valid for all apps, more blockstack focused apps. I would argue that all the gaia communications should be handled in one service component.

Just for completeness again:
The application context is used 
* to lookup resources (for javascript files)
* to retrieve default shared preferences (via SessionStore)

The activity context is required
* to redirect the user to sign in

A way to solve this issue could be to move `redirectToSignIn` to a new object `BlockstackSignIn`.

**Comment by sdsantos** [comment]
@friedger Just to follow-up on
> Going back would close the browser and not back to the app.

From what I tried, when calling `context.startActivity` with the flag `Intent.FLAG_ACTIVITY_NEW_TASK` the back button still returns to app. I believe this is a method used by other libraries to only require the application context.

**Comment by friedger** [comment]
This works only because you didn't do anything in between. Press home, open another app (e.g. answer the phone) then come back to the app and press back.

**Comment by friedger** [comment]
Version 0.5.0 introduces a `BlockstackSignIn` object that use an activity context and is only used for sign in.
