### ISSUE TITLE
Android API Version to Support

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#2]
Adding some notes here about my decisions regarding API version support.

This is google's information about android version support by devices in current use:

<img width="1103" alt="screen shot 2018-03-16 at 4 52 36 pm" src="https://user-images.githubusercontent.com/597182/37511616-755fc900-293a-11e8-9909-804e1bca99e3.png">

I'm trying to support API 15 as the minimum API version initially, but might bump up the version a bit if it becomes too time consuming. Current version in android 8.1.0 is API 27 - that's what my test device is using.

**Comment by amorenew** [comment]
As every new app I started today I make minimum sdk 21.
Any app below API 21 will be 1g ram or less so people change there devices to 2g ram otherwise it is very slow for most of apps.

**Comment by larrysalibra** [comment]
Thanks for the feedback @amorenew - what do you think about min api @friedger ?

**Comment by friedger** [comment]
@larrysalibra I think that an SDK should impose as little as possible on the customer apps. The customer apps can decide based on the version distribution.

The SDK providers should decide on technical considerations. API 19 (Kitkat) introduces a better webview (https://developer.android.com/guide/webapps/migrating), hence that would be a good min API.

**Comment by larrysalibra** [comment]
Thanks @amorenew and @friedger for your feedback. Let's start out with min API of 19 and we can always bump it up later if needed.
