### ISSUE TITLE
As a developer, I want to use the blockstack session object in the background

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#23]
Is it possible to create the blockstack session in a non-UI thread? E.g. when using dependency injection.

The issue is that the session depends on the webview and there are some checks in the there about threads (as far as I remember)

**Comment by friedger** [comment]
Maybe this issue should be split in two: one about background, one about synchronisation

**Comment by larrysalibra** [comment]
@friedger has created a branch https://github.com/blockstack/blockstack-android/tree/feature/service
to try this out, but the UI freezes when the webview is created.

1.) option is to rewrite the get/put file methods entirely in kotlin
2.) another option might be to only create the webview to do the encryption and the gaia credential generation and destroy it after - not sure if this works if it'd would be any faster than 1.

Either way, I think we should hold off on this until we have api parity to blockstack.js unless developers start requesting this functionality. 

If you're reading this and want this functionality, please leave a comment!

**Comment by friedger** [comment]
blockstack.js is about to come without dependencies to local storage and a user session object. This is what we need for this issue!

Using duktape-android instead of WebView, I managed to use a blockstack.js with the following changes to blockstack.js:
* globally replace `window.FormData` with `undefined`
* remove "use strict" in the first line.
* add `var blockstack = {};` at the top of the file (blockstack is the standalone name in browserify)
* in line to replace `g=f();` with `blockstack=f();`

Furthermore, define a javascript console by injecting a java object via 
`duktape.set("console", Console::class.java, myConsole)`

**Comment by friedger** [comment]
fixed by #103
