### ISSUE TITLE
Consider using Storage Access Framework

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#32]
In @friedger ‘s talk he suggested we use SAF for Gaia storage on android ![0a566a22-d07f-427a-9b3d-a0a3ad40e6eb](https://user-images.githubusercontent.com/597182/41967519-14f1b704-7a02-11e8-93a2-92d3b8d4a433.jpeg)

**Comment by friedger** [comment]
This requires some kind of list files API. @larrysalibra Is there an feature request for that?

**Comment by friedger** [comment]
With #110  this is possible. See discussion and sample code at https://forum.blockstack.org/t/next-steps-of-android-integration/6627
