### ISSUE TITLE
Tag releases without 'v'

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#36]
The current release requires the following import:

```
implementation 'com.github.blockstack:blockstack-android:v0.2.0'
```

Commonly, the following style is used:

```
implementation 'com.github.blockstack:blockstack-android:0.2.0'
```

**Comment by larrysalibra** [comment]
I'll start tagging releases like this starting from today's release of 0.3.0

**Comment by larrysalibra** [comment]
Done! 
https://github.com/blockstack/blockstack-android/releases/tag/0.3.0
