### ISSUE TITLE
Warning: "kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead"

### ISSUE THREAD

**Issue by altuncu** [blockstack/blockstack-android#40]
When I add Blockstack SDK into my project's build.gradle, it gives a warning like the following:

".../kotlin-stdlib-jre7-1.2.31.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead"

Because of this warning, build fails. So, please upgrade that library.

**Comment by larrysalibra** [comment]
@altuncu this is now fixed in the latest develop - will be in release v0.3.0 - thanks for reporting!!
