### ISSUE TITLE
Set up circle ci

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#50]

**Comment by larrysalibra** [comment]
@friedger CircleCI 2.0 is now configured: 
https://github.com/blockstack/blockstack-android/commit/5d06ffd55b07617c6a9f338bbfb362dbf3053740

Please close this issue if it works for you!

**Comment by friedger** [comment]
The cache operations fail: https://circleci.com/gh/blockstack/blockstack-android/7 
Furthermore, should the upload of test reports be blockstack-android-sdk instead of blockstack-sdk?

**Comment by friedger** [comment]
Issue fixed by https://github.com/blockstack/blockstack-android/pull/65/commits/d6da44af62a263e7812ecd4445cfbd94f07f1b9a
