### ISSUE TITLE
Make react-native example app

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#55]
Provide a simple example app using reactive-native that 
* allows to sign in/sign out
* put a file and read a file

**Comment by friedger** [comment]
For reference: 
* iOS pull request: https://github.com/blockstack/blockstack-ios/pull/10
* android react native documentation: https://facebook.github.io/react-native/docs/native-modules-android

**Comment by QQ10388577** [comment]
你好！请问你那边有React Native ios APP上架的技术或者有认识的朋友可以合作吗？打扰见谅！zhaoshangjia AT outlook.com

**Comment by friedger** [comment]
The code is available at https://github.com/friedger/blockstack-react-native

**Comment by friedger** [comment]
There is now an official repo: https://github.com/blockstack/blockstack-react-native

**Comment by friedger** [comment]
More issues can be opened in the official Blockstack RN repo: https://github.com/blockstack/blockstack-react-native
