### ISSUE TITLE
Guidelines for collaboration and first issues?

### ISSUE THREAD

**Issue by dustedrob** [blockstack/blockstack-android#57]
Hi, I would love to start contributing to the project, though it appears that there aren't any active good first issues. What's the best way to get involved? Thanks!

**Comment by friedger** [comment]
Hi Roberto, 

As a contributor you have to signe the CLA: https://cla-assistant.io/blockstack/blockstack-android

Do you have an existing android app where you could integrate blockstack? Please try and report back on forum.blockstack.org what issues you had, what was difficult to use? 

Also if you have experience with react-native you can tackle #55

**Comment by larrysalibra** [comment]
We now have guide lines for contribution here: 
https://github.com/blockstack/blockstack-android/blob/master/CONTRIBUTING.md
