### ISSUE TITLE
Set up firebase test lab to automate integration tests

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#62]
CircleCi isn't able to run Android integration tests...only unit tests.

Here's a guide for setting up firebase test lab to handle emulated or real device integration tests:

https://medium.com/@ayltai/all-you-need-to-know-about-circleci-2-0-with-firebase-test-lab-2a66785ff3c2

**Comment by larrysalibra** [comment]
Pinged @wileyj on slack asking if he can set up a firebase project for this and invite @friedger

**Comment by friedger** [comment]
Fixed by #74
