### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by altuncu** [blockstack/blockstack-android#69]
The arguments of the class BlockstackSession() has almost totally changed in v0.3.0. So, please update "Tutorial.md" according to the new structure of the SDK. Also, the line "implementation 'com.github.blockstack:blockstack-android:v0.3.0'" should be changed as "implementation 'com.github.blockstack:blockstack-android:0.3.0'"

**Comment by friedger** [comment]
Thank you for the remarks. You are right!

Do you want to edit the file and send a pull request?

**Comment by moxiegirl** [comment]
@friedger I'll do that PR. Give me a sec.

**Comment by moxiegirl** [comment]
@friedger My understanding from @larrysalibra  is that we were waiting for you to finish work before updating the tutorial.md again. @larrysalibra what do you think?

I've created a PR for the typo in the version which is a small change that can go in right away.  I think we need a different issue for the larger work of reworking and testing the tutorial after @friedger work is in.
