### ISSUE TITLE
As a user, I am confused when the redirect after sign in is taken by more than one app

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#7]
The redirect after sign in launches an intent with the specified schema. A second app could use the same schema and the user has to choose which app should receive the auth token.

![screenshot_1523512834](https://user-images.githubusercontent.com/1449049/38659067-0103b96a-3e28-11e8-8847-a36495622a23.png)

**Comment by friedger** [comment]
Instead of using a custom schema the app should use the intent: schema as described here
https://developer.chrome.com/multidevice/android/intents and here https://bugzilla.mozilla.org/show_bug.cgi?id=851693

**Comment by larrysalibra** [comment]
That makes sense - will have to coordinate with @yknl because I think the iOS app is also using custom schemas.

Another alternative is to use app links/universal links. What are your thoughts on those @friedger ?

**Comment by friedger** [comment]
App links require that they are verified in order to uniquely resolve to a single activity. This creates an extra burden to the developer, especially if the app is not associated with a particular domain. This holds for note pad apps or the like.

In Android apps do not "own" a custom schema.

For authentication, I think the SDK should make sure that the result indeed arrives at the correct package name/app.

**Comment by larrysalibra** [comment]
> App links require that they are verified in order to uniquely resolve to a single activity. This creates an extra burden to the developer,

Yes I found the verification process to be burdensome which is one reason to use schemas.

> especially if the app is not associated with a particular domain

Just to be clear, Blockstack apps have to be associated with a particular domain even if there's not a web version of the app.

**Comment by friedger** [comment]
Discussing with @larrysalibra : App links is the way to go.

**Comment by friedger** [comment]
@larrysalibra Do you have a domain for app links we can use for the examples?

**Comment by larrysalibra** [comment]
@friedger we don't right now.

we could register one.

do you have a domain you can use for development and then we can change it to one we register later?

**Comment by friedger** [comment]
Documentation has been updated to describe app links in favor of custom protocols.
