### ISSUE TITLE
Update to blockstack.js v18.0.4

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-android#76]
We'll need to test this to make sure the mobile redirect changes don't effect the android SDK.

**Comment by friedger** [comment]
What is that exactly?

**Comment by larrysalibra** [comment]
There was a change in the sign in flow protocol detection in blockstack.js 18.0.4 that redirects users to browser.blockstack.org if their user agent string is a mobile device.

**Comment by larrysalibra** [comment]
This will be in the next release!
