### ISSUE TITLE
[feature-request] No mechanism to get public key.

### ISSUE THREAD

**Issue by AC-FTW** [blockstack/blockstack-android#78]
In examining this API and it's runtime objects, I see no way to get the application's public key.

In other Blockstack API's I used getPublicKeyFromPrivate, but I'm not seeing that method exposed in Kotlin or called in Kotlin.

At runtime, the UserData object features the application's private key, but does not have the public key--it is also not in the json getter for the UserData object (for unexposed properties).

Did I miss something?

**Comment by AC-FTW** [comment]
After poking through Blockstack.js, I can see that encryptContent is implicitly calling getPublicKeyFromPrivate for me. That's great.

Unfortunately, what happens when I want to encrypt with another user's public key? How do I tell the Blockstack.js encryptContent method to use that key if I have it?

On Desktop Blockstack.js, I think a lot of the existing product is directly calling encryptECIES.js to do this. Not sure what's happening on the official iOS API as we're using different code to achieve interop cryptography with Blockstack.js.

**Comment by AC-FTW** [comment]
Related feature request on blockstack.js: https://github.com/blockstack/blockstack.js/issues/535

**Comment by friedger** [comment]
I think this has been solved in blockstack.js and the android API reflects the possibility to use other users' public keys.

Maybe a radiks SDK for Android can help even more to simplify the exchange of public keys...

I am closing this one for now. Please open a new issue if you think that there is something missing in the Android API.
