### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-android#81]
The following APIs of 18.0.4 of blockstack.js are not available in the SDK:

* isSignInPending 
* makeAuthRequest 
* generateAndStoreTransitKey 
* redirectToSignInWithAuthRequest 
* getAuthResponseToken 

*  extractProfile
* wrapProfileToken
* signProfileToken
* verifyProfileToken
* validateProofs

* getAppBucketUrl
* getUserAppFileUrl

**Comment by larrysalibra** [comment]
This will be in the next release.
