### ISSUE TITLE
Expand tutorial and current reference into blockstack.js Developer Guide

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-android#91]
@friedger  suggested we build out a similar guide (simpler of course) https://developer.android.com/guide/

Currently, we have:

- tutorial (hello world)
- reference
- three more sophisticated but undocumented examples

**Comment by friedger** [comment]
@moxiegirl I added some paragraphs in the README (See https://github.com/blockstack/blockstack-android/pull/123) Should this stay there or go somewhere else? Should we generate documentation from the example codes? So that we can maintain the code only in the source folder?

**Comment by moxiegirl** [comment]
@friedger Well, when it comes to API reference it makes sense to generate it from the source code. Tutorials are a bit problematic, depends on the tool of course. Do you have one in mind?
